# Very nice hyperparameters
model:
  image_shape: [320, 240]
  initial_channel: 42
  num_blocks: 
    - 2
    - 3
    - 5
    - 2
  channels: 
    - 42
    - 64
    - 196
    - 384
    - 768
  block_type: 
    - C
    - C 
    - T
    - T
  dropout: 0.0

exp:
  exp_name: "1023_2"
  learning_rate: 0.005
  grad_accu: 6
  batch_size: 10
  epochs: 20
  betas: [0.96, 0.98]
  alpha: 0.7
  cache_dir: "/content/drive/MyDrive/brainstormers/cache.hdf5"
  checkpoint_dir: "/content/drive/MyDrive/brainstormers/231023"
  image_dir: "/content/dataset"
  num_to_samples: 5
  how_many_to_save: 5

  metrics:
    - l2
    - kl
  optimizer: "SGD"
  weight_decay: 0.01
  grad_clip: 1.0
  log: True
