# Very nice hyperparameters
# Best trial:
#   Value:  0.001003670389764011
#   Params: 
#     dropout: 0.035140161509175816
#     third_layer: 2
#     forth_layer: 4
#     optimizer: Adam
#     lr: 0.0007737297489778149
#     weight_decay: 0.0010272784773375425
#     grad_clip: 1
model:
  image_shape: [320, 240]
  initial_channel: 42
  num_blocks: 
    - 2
    - 2
    - 2
    - 4
  channels: 
    - 42
    - 64
    - 196
    - 384
    - 768
  block_type: 
    - C
    - C 
    - T
    - T
  dropout: 0.035140161509175816

exp:
  model_name: "coatnet"
  exp_name: "1025_final"
  learning_rate: 0.00077
  grad_accu: 1
  batch_size: 1
  epochs: 50
  betas: [0.96, 0.99]
  alpha: 0.9
  cache_dir: "/content/drive/MyDrive/brainstormers/cache.hdf5"
  checkpoint_dir: "/content/drive/MyDrive/brainstormers/231025"
  image_dir: "/content/dataset"
  num_to_samples: 5
  how_many_to_save: 5
  output_scale: 0.01
  seed: 1123498
  just_one_pre_run: False
  save_term: 1

  metrics:
    - l2
    - cos
  optimizer: "Adam"
  weight_decay: 0.0010272784773375425
  grad_clip: 1.0
  log: True
