model:
  image_shape: [320, 240]
  initial_channel: 42
  num_blocks: 
    - 1
    - 1
    - 1
    - 1
  channels: 
    - 42
    - 64
    - 196
    - 384
    - 768
  block_type: 
    - C
    - C
    - C
    - T
  dropout: 0.1

exp:
  exp_name: "1025_singlebatch_2"
  learning_rate: 0.005
  grad_accu: 1
  batch_size: 1
  epochs: 400
  betas: [0.96, 0.99]
  alpha: 0.9
  cache_dir: "/content/drive/MyDrive/brainstormers/cache.hdf5"
  checkpoint_dir: "/content/drive/MyDrive/brainstormers/231025"
  image_dir: "/content/dataset"
  num_to_samples: 5
  how_many_to_save: 5
  output_scale: 0.01
  seed: 1123498
  just_one_pre_run: True
  save_term: 5

  metrics:
    - l2
    - cos
  optimizer: "AdamW"
  weight_decay: 0.01
  grad_clip: 1.0
  log: True
